apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk024-my-app
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk024-my-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/actuator/prometheus"
        update: b4b0bfcf04c7cd0f658321d02714cb5d
      labels:
        app: sk024-my-app
    spec:
      serviceAccountName: default
      containers:
        - name: my-app
          image: amdp-registry.skala-ai.com/skala25a/sk024-my-app@sha256:e8bafde393ecaab4cb73f0bb1d4d81456fc0120c547036ae1d8894df046922d8
          imagePullPolicy: Always
          env:
            - name: LOGGING_LEVEL
              value: DEBUG
            - name: USER_NAME
              value: sk024
            - name: NAMESPACE
              value: skala-practice
