server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/stockapp;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

  resources:
    static-locations: classpath:/static/

management:
  server:
    port: 8081 # Actuator 포트 설정
  endpoints:
    web:
      exposure:
        include: "*" # Prometheus endpoint 노출
  metrics:
    enable:
      all: true # 모든 기본 메트릭 활성화
  endpoint:
    prometheus:
      enabled: true # Prometheus endpoint 활성화

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  swagger-ui:
    path: /swagger/swagger-ui # Swagger UI 접속 경로 변경
  api-docs:
    path: /swagger/swagger-docs
