apiVersion: v1
kind: Service
metadata:
  name: skala-stock-ui
  namespace: skala-edu
spec:
  selector:
    app: skala-stock-ui
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: mgmt
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
